leftnav:
- identifier: 0e63f2de-4b07-b833-bfb1-18e469a12a1e
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 1c43d624-ee12-198a-8382-22e3fa098f69
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: a29df737-820a-7b0a-d65f-2f8cdb8c112c
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: fb1058c5-e62c-bac5-833d-ebf14535f227
  name: Assignments
  url: /pages/assignments
  weight: 40
